Time Complexity

Accessing an Element:
Operation: Accessing an element by index.

 Complexity: O(1)

Explanation: Array access is constant time since the position can be directly computed using the index.

In [1]:
array = [10, 20, 30, 40, 50]
# Accessing the element at index 2
element = array[2]
print(element)  # Output: 30


30


Insertion at End:
Operation: Appending an element to the end of the array.

Complexity: O(1) (amortized)

Explanation: Appending to the end is generally O(1), though occasionally resizing can make it O(n) in dynamic arrays like Python lists.

In [ ]:
array = [1, 2, 3]
array.append(4)
print(array)  # Output: [1, 2, 3, 4]

Insertion at a Specific Position:	
Operation: Inserting an element at a specific index.

Complexity: O(n)

Explanation: Inserting requires shifting elements to accommodate the new item, resulting in linear time complexity.

In [ ]:
array = [1, 2, 4, 5]
array.insert(2, 3)  # Inserting 3 at index 2
print(array)  # Output: [1, 2, 3, 4, 5]


Deletion:
Operation: Removing an element from a specific index.

Complexity: O(n)

Explanation: Deletion requires shifting elements to fill the gap, resulting in linear time complexity.

In [ ]:
array = [1, 2, 3, 4, 5]
del array[2]  # Deleting element at index 2
print(array)  # Output: [1, 2, 4, 5]

Searching:

Operation: Linear search.

Complexity: O(n)

Explanation: Linear search checks each element until the target is found, making it linear in time complexity.


In [ ]:
array = [1, 2, 3, 4, 5]
def linear_search(arr, target):
    for index, value in enumerate(arr):
        if value == target:
            return index
    return -1

print(linear_search(array, 4))  # Output: 3

Space Complexity
Space Complexity for One-Dimensional Arrays:
Complexity: O(n)
Explanation: The space complexity of an array is proportional to the number of elements it contains.

In [ ]:
array = [1] * 1000  # Array with 1000 elements

Two-Dimensional Arrays

1. Time Complexity
1.	Accessing an Element:
Operation: Accessing an element by row and column index.
Complexity: O(1)
Explanation: Accessing an element in a 2D array is constant time, as it directly computes the address.

In [ ]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# Accessing the element at row 1, column 2
element = matrix[1][2]
print(element)  # Output: 6

2.	Traversal:
Operation: Traversing all elements in the 2D array.
Complexity: O(n * m) where n is the number of rows and m is the number of columns.

Explanation: Traversing every element in a 2D array involves visiting each element once, resulting in O(n * m) complexity.


In [ ]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

for row in matrix:
    for element in row:
        print(element, end=' ')
# Output: 1 2 3 4 5 6 7 8 9

3.	Insertion:
Operation: Inserting a row or column.
Complexity: O(n * m) (for inserting and shifting elements)


Explanation: Inserting a new row involves creating a new matrix and copying the elements, resulting in linear complexity relative to the size of the matrix.


In [ ]:
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Adding a new row
new_row = [7, 8, 9]
matrix = np.vstack([matrix, new_row])
print(matrix)
# Output:
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

4.	Deletion:
Operation: Removing a row or column.
Complexity: O(n * m) (for removing and shifting elements)


Explanation: Deleting a row or column involves creating a new matrix and copying elements, resulting in linear complexity relative to the size of the matrix.


In [ ]:
import numpy as np

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Removing a row
matrix = np.delete(matrix, 1, axis=0)  # Removing row at index 1
print(matrix)
# Output:
# [[1 2 3]
#  [7 8 9]]

5.	Searching:
Operation: Linear search in 2D array.
Complexity: O(n * m)


Explanation: Searching in a 2D array involves checking each element, resulting in linear complexity relative to the number of elements.


In [ ]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

def search_2d(arr, target):
    for row in arr:
        for element in row:
            if element == target:
                return True
    return False

print(search_2d(matrix, 5))  # Output: True

Space Complexity
1.	Space Complexity for Two-Dimensional Arrays:
Complexity: O(n * m)

Explanation: The space complexity of a 2D array is proportional to the product of the number of rows and columns.


In [ ]:
matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]