Graphs Agenda

    What is Graph? Types of Graphs
    Graph Terminologies and Applications
    Graph Representation (adjacency matrix/list)
    Implement Graph Algorithms
    Traversal – BFS Algorithms
    Traversal – DFS Algorithms
    Graphs - Connected Components

Graphs are versatile data structures used to represent and analyze relationships between objects. 

They are used in a wide range of applications, including social networks, recommendation systems, and network routing.

A graph consists of vertices (or nodes) and edges (connections between vertices).

It can represent various types of relationships or connections.

Types of Graphs:

    Undirected Graph: Edges have no direction. The connection between vertices u and v is bidirectional.

    Directed Graph (Digraph): Edges have direction. The connection from u to v is one-way.

    Weighted Graph: Edges have weights representing the cost or distance between vertices.

    Unweighted Graph: Edges do not have weights; all edges are equal.

    Cyclic Graph: Contains at least one cycle (a path that starts and ends at the same vertex).

    Acyclic Graph: Contains no cycles.

    Connected Graph: There is a path between every pair of vertices.

    Disconnected Graph: Some vertices are not reachable from others.

    Complete Graph: Every pair of distinct vertices is connected by a unique edge.

Graph Terminologies

1.	Vertex (Node): The fundamental unit of a graph, representing an entity or point.

2.	Edge (Arc): The connection between two vertices. In directed graphs, an edge has a direction from one vertex to another.

3.	Degree: The number of edges connected to a vertex. In a directed graph, there are in-degrees (number of incoming edges) and out-degrees (number of outgoing edges).

4.	Path: A sequence of edges connecting a sequence of vertices. A path that starts and ends at the same vertex is called a cycle.

5.	Cycle: A path that starts and ends at the same vertex, with no repeated edges or vertices (except the starting and ending vertex).

6.	Subgraph: A graph formed from a subset of the vertices and edges of a larger graph.

7.	Connected Component: A maximal subset of vertices such that there is a path between every pair of vertices within the subset.

8.	Tree: A special type of graph that is connected and acyclic. Every tree is a graph, but not all graphs are trees.

9.	Forest: A collection of disjoint trees.

10.	Graph Traversal: Techniques to visit all vertices and edges of a graph, usually in a systematic way. Common methods include BFS and DFS.

11.	Shortest Path: The path between two vertices with the minimum sum of edge weights. Algorithms like Dijkstra’s or Bellman-Ford are used to find the shortest path.

12.	Minimum Spanning Tree (MST): A subset of edges in a weighted graph that connects all vertices with the minimum possible total edge weight. Kruskal’s and Prim’s algorithms are used to find MSTs.

13.	Topological Sort: An ordering of vertices in a Directed Acyclic Graph (DAG) where for every directed edge from vertex u to vertex v, u comes before v in the ordering.

14.	Adjacency Matrix: A 2D array used to represent a graph, where the cell at row i and column j indicates the presence (or absence) of an edge between vertex i and vertex j.

15.	Adjacency List: A list where each vertex has a list of adjacent vertices, representing the edges connected to that vertex.

16.	Graph Density: The ratio of the number of edges in the graph to the number of possible edges. It measures how "dense" a graph is.

Applications of Graphs
1.	Social Networks: Represent relationships between users. Nodes represent people, and edges represent friendships or connections.

2.	Web Page Link Analysis: Websites and their hyperlinks are represented as graphs. Algorithms like PageRank use graph theory to rank web pages.

3.	Routing and Navigation: Used in GPS and mapping services to find the shortest path between locations. Nodes represent locations, and edges represent possible paths.

4.	Network Design: In telecommunications and computer networks, graphs model the layout of network components and connections.

5.	Recommendation Systems: Graphs are used to represent user preferences and item relationships. Collaborative filtering methods use graphs to recommend items to users.

6.	Task Scheduling: Directed Acyclic Graphs (DAGs) represent tasks and their dependencies. Used in project management and scheduling algorithms.

7.	Biological Networks: Represent interactions between genes, proteins, or other biological entities. Graphs are used to study the structure and function of biological systems.

8.	Game Theory: Graphs model possible states and moves in games. They help in analyzing strategies and game outcomes.

9.	Computer Vision: Used to represent images as graphs where pixels or regions are nodes, and edges represent relationships between them. Useful in image segmentation and object detection.

10.	Fraud Detection: In financial transactions or social media, graphs help detect unusual patterns or relationships that may indicate fraudulent activities.

11.	Circuit Design: Graphs model electrical circuits where components like resistors and transistors are vertices, and connections are edges.


Graph Representation

Graphs can be represented using different data structures:

    Adjacency Matrix: A 2D array where the element at (i,j) is true (or the weight of the edge) if there is an edge between vertices i and j.
    

    Adjacency List: An array of lists where each list contains the neighbors of a vertex.

Adjacency Matrix Example

Adjacency Matrix Representation

In an adjacency matrix, we use a 2D array (list of lists) to represent the graph. 

If there is an edge between two vertices, 
the matrix entry is 1 
(or the weight of the edge, for a weighted graph); 
otherwise, it's 0.

Example: Undirected Graph
Let's consider the following undirected graph:
A -- B
|    |
C -- D
Python Code for Adjacency Matrix:

In [11]:
# Define the vertices of the graph
vertices = ['A', 'B', 'C', 'D']

# Create an adjacency matrix (4x4) initialized with zeros
adjacency_matrix = [[0 for _ in range(len(vertices))] for _ in range(len(vertices))]

print(adjacency_matrix)

# Define the edges of the graph (undirected)
edges = {
    ('A', 'B'): 1,
    ('A', 'C'): 1,
    ('B', 'D'): 1,
    ('C', 'D'): 1
}

print("edges of Adjacency Matrix:",edges)

# Fill the adjacency matrix based on the edges
for (start, end), weight in edges.items():
    i = vertices.index(start)
    j = vertices.index(end)
    adjacency_matrix[i][j] = weight
    adjacency_matrix[j][i] = weight  # Since it's an undirected graph

# Print the adjacency matrix
print("Adjacency Matrix:")
for row in adjacency_matrix:
    print(row)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
edges of Adjacency Matrix: {('A', 'B'): 1, ('A', 'C'): 1, ('B', 'D'): 1, ('C', 'D'): 1}
Adjacency Matrix:
[0, 1, 1, 0]
[1, 0, 0, 1]
[1, 0, 0, 1]
[0, 1, 1, 0]


Adjacency Matrix

    An adjacency matrix is a 2D array where the cell at position [i] [j] indicates the presence (and weight, if applicable) of an edge between 
    vertex i and vertex j

    For an Undirected Graph: The matrix is symmetric. 
    If there's an edge between i and j, then both [i] [j]  and [j] [i] will have the same value (usually 1 or the weight of the edge).

    For a Directed Graph: The matrix is not necessarily symmetric. [i] [j] represents an edge from vertex i to vertex j.

In [1]:
# Example for an undirected graph with 4 vertices
graph = [
    [0, 1, 1, 0],  # Vertex 0
    [1, 0, 1, 1],  # Vertex 1
    [1, 1, 0, 1],  # Vertex 2
    [0, 1, 1, 0]   # Vertex 3
]
print(graph)

[[0, 1, 1, 0], [1, 0, 1, 1], [1, 1, 0, 1], [0, 1, 1, 0]]


In [12]:
import numpy as np

class GraphAdjMatrix:
    def __init__(self, vertices):
        '''Initializes the graph with the number of vertices'''
        self.vertices = vertices # Total number of vertices
        self.adj_matrix = np.zeros((vertices, vertices), dtype=int)

    def add_edge(self, u, v, weight=1):
        ''' Add an edge between vertices u and v '''
        self.adj_matrix[u][v] = weight # For directed graphs
        # For undirected graphs, also set the opposite edge
        self.adj_matrix[v][u] = weight # For undirected graphs

    def display(self):
        ''' Print the adjacency matrix '''
        print(self.adj_matrix)

# Usage
g = GraphAdjMatrix(4)
g.add_edge(0, 1, 5)
g.add_edge(1, 2, 3)
g.add_edge(2, 3, 2)
g.add_edge(3, 0, 4)

g.display()

g1 = GraphAdjMatrix(4)
g1.add_edge(0, 1)
g1.add_edge(1, 2)
g1.add_edge(2, 3)
g1.add_edge(3, 0)
g1.display()

[[0 5 0 4]
 [5 0 3 0]
 [0 3 0 2]
 [4 0 2 0]]
[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


Adjacency List

    An adjacency list represents a graph as a list where 
    each index corresponds to a vertex, and 
    each entry in the list is a list of adjacent vertices. 
    This representation is more space-efficient for sparse graphs.

Adjacency List Example:

In [19]:
# Example for an undirected graph with 4 vertices
graph = {
    0: [1, 2],
    1: [0, 2, 3],
    2: [0, 1, 3],
    3: [1, 2]
}
print(graph)

graph_list = [
    [1, 2],      # Node 0 is connected to nodes 1 and 2
    [0, 2, 3],   # Node 1 is connected to nodes 0, 2, and 3
    [0, 1, 3],   # Node 2 is connected to nodes 0, 1, and 3
    [1, 2]       # Node 3 is connected to nodes 1 and 2
]

print(graph_list)
print(graph_list[0])
print(graph_list[1])
print(graph_list[2])
print(graph_list[3])

{0: [1, 2], 1: [0, 2, 3], 2: [0, 1, 3], 3: [1, 2]}
[[1, 2], [0, 2, 3], [0, 1, 3], [1, 2]]
[1, 2]
[0, 2, 3]
[0, 1, 3]
[1, 2]


The graph can be visualized like this:
    0
   / \
  1---2
   \ /
    3

•	Node 0 is connected to nodes 1 and 2.
•	Node 1 is connected to nodes 0, 2, and 3.
•	Node 2 is connected to nodes 0, 1, and 3.
•	Node 3 is connected to nodes 1 and 2.


Breakdown of the Graph:

•	Key 0: The list [1, 2] indicates that node 0 is connected to nodes 1 and 2.
•	Key 1: The list [0, 2, 3] indicates that node 1 is connected to nodes 0, 2, and 3.
•	Key 2: The list [0, 1, 3] indicates that node 2 is connected to nodes 0, 1, and 3.
•	Key 3:The list [1, 2] indicates that node 3 is connected to nodes 1 and 2.


•	0 is connected to 1 and 2.
•	1 is connected to 0, 2, and 3.
•	2 is connected to 0, 1, and 3.
•	3 is connected to 1 and 2.
This is an undirected graph since the connections go both ways (i.e., 0 is connected to 1, and 1 is connected to 0, and so on).


This list-based representation corresponds directly to the adjacency list. 

For example:
•	graph_list[0] is [1, 2], meaning node 0 is connected to nodes 1 and 2.
•	graph_list[1] is [0, 2, 3], meaning node 1 is connected to nodes 0, 2, and 3.

In [20]:
class GraphAdjList:
    ''' Graph represented as an adjacency list '''
    def __init__(self):
        self.graph = {}   # The graph is initially empty

    def add_vertex(self, vertex):
        '''Add a new vertex to the graph'''
        if vertex not in self.graph:
            self.graph[vertex] = []  # No edges incident on this vertex

    def add_edge(self, u, v):
        '''Add an edge between vertices u and v'''
        if u not in self.graph:
            self.add_vertex(u) # Add u to the graph

        if v not in self.graph:
            self.add_vertex(v) # Add v to the graph

        self.graph[u].append(v) # Add v to u's list of neighbors

        # For undirected graphs, also add the reverse edge
        self.graph[v].append(u) # Add u to v's list of neighbors

    def display(self):
        ''' Print the graph '''
        for vertex in self.graph:
            print(f"{vertex}: {self.graph[vertex]}")

# Usage
g = GraphAdjList()
g.add_edge(1, 2)
g.add_edge(1, 3)
g.add_edge(2, 4)
g.add_edge(3, 4)

g.display()

1: [2, 3]
2: [1, 4]
3: [1, 4]
4: [2, 3]


Implement Graph
A basic implementation of a graph using an adjacency list in Python:

In [21]:
class Graph:
    def __init__(self):
        self.graph = {} # dictionary to store the graph

    def add_vertex(self, vertex):
        if vertex not in self.graph:
            self.graph[vertex] = [] # Add a new vertex

    def add_edge(self, vertex1, vertex2):
        if vertex1 in self.graph and vertex2 in self.graph:
            self.graph[vertex1].append(vertex2)
            self.graph[vertex2].append(vertex1)  # For undirected graph

    def __str__(self):
        return str(self.graph) # Print the graph

g = Graph()
g.add_vertex(0)
g.add_vertex(1)
g.add_vertex(2)
g.add_vertex(3)
g.add_edge(0, 1)
g.add_edge(0, 2)
g.add_edge(1, 2)
g.add_edge(1, 3)
print(g)

{0: [1, 2], 1: [0, 2, 3], 2: [0, 1], 3: [1]}


Traversal - BFS (Breadth-First Search)

    Breadth-First Search explores nodes level by level, 
    starting from the root (or any arbitrary node) and 
    visiting all neighbors before moving to the next level.

In [22]:
from collections import deque

def bfs(graph, start):
    ''' Breadth-first search '''
    visited = set() # Set to keep track of visited nodes
    queue = deque([start]) # Initialize the queue
    visited.add(start) # Mark the start node as visited

    while queue:
        vertex = queue.popleft() # Get the next vertex
        print(vertex, end=' ')  # Print the vertex

        for neighbor in graph.get(vertex, []):  # Visit all neighbors
            if neighbor not in visited:
                visited.add(neighbor) # Mark the neighbor as visited
                queue.append(neighbor) # Add the neighbor to the queue

graph = { 0: [1, 2], 1: [0, 2, 3], 2: [0, 1, 3], 3: [1, 2] }

bfs(graph, 0)  # 0 1 2 3

0 1 2 3 

Breadth-First Search (BFS)

    Breadth-First Search (BFS) is a graph traversal algorithm that explores all the neighbors of a node before moving to the next level of neighbors.

BFS Algorithm:

    1.Start from a source node.
    2.Visit all its neighbors before moving on to the neighbors of those neighbors.
    3.Use a queue to keep track of the nodes to be visited.

In [36]:
from collections import deque

def bfs(graph, start_node):
    # Initialize a queue for BFS and add the starting node
    queue = deque([start_node]) # A queue to keep track of nodes to visit

    # A set to keep track of visited nodes to avoid cycles
    visited_nodes = set([start_node]) # A set to keep track of visited nodes

    while queue:
        # Dequeue a node from the queue
        current_node = queue.popleft() # Get the front element from the queue
        print(f"Visited: {current_node}")

        # Loop through all adjacent nodes of the current node
        for neighbor in graph[current_node]:
            if neighbor not in visited_nodes:
                queue.append(neighbor)  # Add unvisited neighbors to the queue
                visited_nodes.add(neighbor)  # Mark neighbor as visited


# Graph represented as an adjacency list
graph = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F'],
    'D': ['A'],
    'E': ['F'],
    'F': ['G'],
    'G': ['C']
}

# Perform BFS starting from node 'A'
bfs(graph, 'A')

Visited: A
Visited: B
Visited: C
Visited: D
Visited: E
Visited: F
Visited: G


Traversal - DFS (Depth-First Search)

Depth-First Search explores as far as possible along each branch before backtracking

In [9]:
def dfs(graph, start, visited=None):
    if visited is None:
        visited = set()
    visited.add(start)
    print(start, end=' ')

    for neighbor in graph.get(start, []):
        if neighbor not in visited:
            dfs(graph, neighbor, visited)

graph = { 0: [1, 2], 1: [0, 2, 3], 2: [0, 1, 3], 3: [1, 2] }

dfs(graph, 0)  # 0 1 2 3

dfs(graph, 3)  # 3 1 0 2

0 1 2 3 3 1 0 2 0 1 2 3 

Depth-First Search (DFS)

    Graph traversal algorithm that explores as far as possible along each branch before backtracking.

DFS Algorithm:

    1.Start from the source node.
    2.Recursively explore each branch as deep as possible before backtracking.
    3.Use a stack (implicit in recursion) to keep track of nodes.


In [31]:
def dfs(graph, start_node, visited_nodes=None):
    if visited_nodes is None:
        visited_nodes = set()

    # Mark the current node as visited
    visited_nodes.add(start_node)
    print(f"Visited: {start_node}")

    # Recur for all adjacent nodes
    for neighbor in graph[start_node]:
        if neighbor not in visited_nodes:
            dfs(graph, neighbor, visited_nodes)


# Graph represented as an adjacency list
graph = {
    'A': ['B', 'C'],
    'B': ['D', 'E'],
    'C': ['F'],
    'D': ['J'],
    'E': ['F'],
    'F': [],
    'J': []
}

# Perform DFS starting from node 'A'
dfs(graph, 'A')

Visited: A
Visited: B
Visited: D
Visited: J
Visited: E
Visited: F
Visited: C


In [10]:
def dfs_iterative(graph, start):
    visited = set()
    stack = [start]
    while stack:
        vertex = stack.pop()
        if vertex not in visited:
            visited.add(vertex)
            print(vertex, end=' ')
            stack.extend(reversed(graph.get(vertex, [])))

graph = { 0: [1, 2], 1: [0, 2, 3], 2: [0, 1, 3], 3: [1, 2] }

dfs_iterative(graph, 0)  # 0 2 3 1

0 1 2 3 

Graphs - Connected Components

    To find connected components in a graph, 
    perform a DFS/BFS for each unvisited vertex. 
    Each DFS/BFS run identifies one connected component.

In [39]:
# Find the connected components of an undirected graph
def connected_components(graph):
    ''' Find the connected components of an undirected graph '''
    visited = set()
    components = []

    for vertex in graph: # Loop through all vertices
        if vertex not in visited: # Start a new component
            component = []
            stack = [vertex] # Initialize the stack

            while stack:
                v = stack.pop() # Get the next vertex from the stack
                if v not in visited: # Visit the vertex
                    visited.add(v) # Mark as visited
                    component.append(v) # Add to the current component
                    stack.extend(neighbor for neighbor in graph.get(v, []) if neighbor not in visited)
                    # Add all neighbors to the stack
            components.append(component) # Add the component to the list

    return components # Return the list of components

graph = { 0: [1, 2], 1: [0, 2, 3], 2: [0, 1, 3], 3: [1, 2], 4: [5], 5: [4] }

print(connected_components(graph))  # [[0, 1, 2, 3], [4, 5]]

[[0, 2, 3, 1], [4, 5]]


In [38]:
# Find the shortest path between two vertices in an undirected graph
def shortest_path(graph, start, end):
    ''' Find a shortest path in an undirected graph between two vertices using BFS '''
    if start == end:
        return [start]

    queue = deque([(start, [start])])

    while queue:
        vertex, path = queue.popleft()

        for neighbor in graph.get(vertex, []):
            if neighbor == end:
                return path + [neighbor]
            if neighbor not in path:
                queue.append((neighbor, path + [neighbor]))

graph = { 0: [1, 2], 1: [0, 2, 3], 2: [0, 1, 3], 3: [1, 2] }

print(shortest_path(graph, 0, 3))  # [0, 1, 3]

print(shortest_path(graph, 0, 4))  # None

[0, 1, 3]
None


Dijkstra’s Algorithm (Shortest Path)

    Dijkstra's Algorithm finds the shortest path from a source node to all other nodes in a graph with non-negative edge weights.

Dijkstra’s Algorithm:

    1.Initialize distances to infinity for all nodes except the source, which has a distance of 0.
    2.Use a priority queue to explore the node with the smallest tentative distance.
    3.For each neighbor, calculate the potential new path and update if it’s shorter than the known distance.


In [15]:
import heapq

def dijkstra(graph, start_node):
    # Initialize distances to infinity and set the start_node distance to 0
    distances = {node: float('inf') for node in graph}
    distances[start_node] = 0

    # Priority queue to store (distance, node) pairs
    priority_queue = [(0, start_node)]

    while priority_queue:
        # Get the node with the smallest distance
        current_distance, current_node = heapq.heappop(priority_queue)

        # Skip processing if we've already found a better path
        if current_distance > distances[current_node]:
            continue

        # Explore neighbors
        for neighbor, weight in graph[current_node].items():
            distance = current_distance + weight

            # Only update if a shorter path is found
            if distance < distances[neighbor]:
                distances[neighbor] = distance
                heapq.heappush(priority_queue, (distance, neighbor))

    return distances


# Graph with weights represented as an adjacency list
graph_with_weights = {
    'A': {'B': 1, 'C': 4},
    'B': {'A': 1, 'D': 2, 'E': 5},
    'C': {'A': 4, 'F': 1},
    'D': {'B': 2},
    'E': {'B': 5, 'F': 3},
    'F': {'C': 1, 'E': 3}
}

# Find the shortest paths from node 'A'
distances = dijkstra(graph_with_weights, 'A')
print("Shortest distances from A:", distances)

Shortest distances from A: {'A': 0, 'B': 1, 'C': 4, 'D': 3, 'E': 6, 'F': 5}


Kruskal’s Algorithm (Minimum Spanning Tree)

    Kruskal’s Algorithm finds the Minimum Spanning Tree (MST) of a graph by selecting edges in increasing order of weight while avoiding cycles.

Kruskal’s Algorithm:

    1.Sort all edges by weight.
    2.Add edges to the MST one by one, ensuring no cycles are formed.
    3.Use Union-Find to keep track of connected components.

In [16]:
# Class to represent a disjoint set for Union-Find
class DisjointSet:
    def __init__(self, vertices):
        self.parent = {vertex: vertex for vertex in vertices}
        self.rank = {vertex: 0 for vertex in vertices}

    def find(self, vertex):
        if self.parent[vertex] != vertex:
            self.parent[vertex] = self.find(self.parent[vertex])
        return self.parent[vertex]

    def union(self, vertex1, vertex2):
        root1 = self.find(vertex1)
        root2 = self.find(vertex2)

        if root1 != root2:
            if self.rank[root1] > self.rank[root2]:
                self.parent[root2] = root1
            elif self.rank[root1] < self.rank[root2]:
                self.parent[root1] = root2
            else:
                self.parent[root2] = root1
                self.rank[root1] += 1

# Kruskal's Algorithm to find the Minimum Spanning Tree
def kruskal(graph):
    edges = []
    mst = []

    # Collect all edges from the graph
    for node in graph:
        for neighbor, weight in graph[node]:
            edges.append((weight, node, neighbor))

    # Sort the edges by weight
    edges.sort()

    # Initialize the Disjoint Set for tracking connected components
    disjoint_set = DisjointSet(graph.keys())

    # Process edges in increasing order of weight
    for weight, node1, node2 in edges:
        # If node1 and node2 are in different sets, add the edge to the MST
        if disjoint_set.find(node1) != disjoint_set.find(node2):
            disjoint_set.union(node1, node2)
            mst.append((node1, node2, weight))

    return mst

# Graph represented as an adjacency list with edge weights
graph_edges = {
    'A': [('B', 1), ('C', 4)],
    'B': [('A', 1), ('D', 2), ('E', 5)],
    'C': [('A', 4), ('F', 1)],
    'D': [('B', 2)],
    'E': [('B', 5), ('F', 3)],
    'F': [('C', 1), ('E', 3)]
}

# Find the Minimum Spanning Tree (MST)
mst = kruskal(graph_edges)
print("Minimum Spanning Tree:", mst)

Minimum Spanning Tree: [('A', 'B', 1), ('C', 'F', 1), ('B', 'D', 2), ('E', 'F', 3), ('A', 'C', 4)]


Library Management System Using Python Graph Data Structure

    In this implementation, we'll use a graph data structure to represent the relationship between books in a library. 

    For simplicity, let's assume the relationships between books can be based on similar genres or authors. We can represent each book as a node, and edges between books will signify that the two books are related (for example, by genre or author).

We will implement:

    •Adding books to the library
    •Establishing relationships (edges) between books (e.g., similar genres)
    •Searching for related books using Depth-First Search (DFS)
    •Finding clusters of related books (connected components)

Steps of the Implementation:

    1.Graph Representation: Use an adjacency list where each node represents a book, and each edge represents a relationship between two books (e.g., shared author or genre).

    2.Add Books: Function to add a book to the library (graph).

    3.Add Relationship: Function to add an edge between two books to indicate they are related (based on genre or author).

    4.Search Books: Function to search for related books using DFS.

    5.Find Clusters of Related Books: Function to find all groups of related books (connected components).

In [17]:
class Book:
    def __init__(self, isbn, title, author, genre):
        self.isbn = isbn  # ISBN number, unique for each book
        self.title = title  # Title of the book
        self.author = author  # Author of the book
        self.genre = genre  # Genre of the book

    def __repr__(self):
        return f"{self.title} by {self.author} (Genre: {self.genre})"


class LibraryGraph:
    def __init__(self):
        self.graph = {}  # Adjacency list to store books and their relationships

    # Add a new book (node) to the graph
    def add_book(self, book):
        if book.isbn not in self.graph:
            self.graph[book.isbn] = []  # Initialize the adjacency list for this book
            print(f"Book added: {book}")
        else:
            print(f"Book with ISBN {book.isbn} already exists.")

    # Establish a relationship (edge) between two books
    def add_relationship(self, isbn1, isbn2):
        if isbn1 in self.graph and isbn2 in self.graph:
            self.graph[isbn1].append(isbn2)  # Add isbn2 as a neighbor of isbn1
            self.graph[isbn2].append(isbn1)  # Add isbn1 as a neighbor of isbn2
            print(f"Relationship established between ISBN {isbn1} and ISBN {isbn2}")
        else:
            print("One or both ISBNs do not exist in the library.")

    # Depth-First Search (DFS) to find all related books from a given book (starting node)
    def search_related_books(self, isbn, visited=None):
        if visited is None:
            visited = set()  # Set to keep track of visited nodes

        visited.add(isbn)  # Mark the current book as visited
        print(f"Visited book ISBN {isbn}: {self.get_book_by_isbn(isbn)}")

        # Explore all related books (neighbors)
        for neighbor_isbn in self.graph[isbn]:
            if neighbor_isbn not in visited:
                self.search_related_books(neighbor_isbn, visited)

    # Find all clusters of related books (connected components)
    def find_related_clusters(self):
        visited = set()  # Set to track all visited nodes
        clusters = []  # List to store all clusters of related books

        # Iterate through each book in the graph
        for isbn in self.graph:
            if isbn not in visited:
                cluster = []  # List to store the current cluster of related books
                self._dfs_cluster(isbn, visited, cluster)
                clusters.append(cluster)  # Add the found cluster to the list
        return clusters

    # Helper DFS function to find a cluster
    def _dfs_cluster(self, isbn, visited, cluster):
        visited.add(isbn)  # Mark the book as visited
        cluster.append(self.get_book_by_isbn(isbn))  # Add book to the current cluster

        # Recursively visit all related books (neighbors)
        for neighbor_isbn in self.graph[isbn]:
            if neighbor_isbn not in visited:
                self._dfs_cluster(neighbor_isbn, visited, cluster)

    # Helper method to get book details by ISBN
    def get_book_by_isbn(self, isbn):
        for book_isbn in self.graph:
            if book_isbn == isbn:
                for book in books:  # Assuming books is a global list of book objects
                    if book.isbn == book_isbn:
                        return book
        return None


# List to store all book objects
books = [
    Book(9780345816023, "The Testaments", "Margaret Atwood", "Fiction"),
    Book(9780525559474, "The Nickel Boys", "Colson Whitehead", "Historical Fiction"),
    Book(9780593139134, "The Dutch House", "Ann Patchett", "Fiction"),
    Book(9781984822185, "Where the Crawdads Sing", "Delia Owens", "Mystery"),
    Book(9780316517867, "The Night Fire", "Michael Connelly", "Mystery"),
    Book(9781524763169, "Becoming", "Michelle Obama", "Biography")
]

# Initialize the library graph
library = LibraryGraph()

# Add books to the library graph
for book in books:
    library.add_book(book)

# Establish relationships between books (based on genre or other criteria)
library.add_relationship(9780345816023, 9780593139134)  # Fiction books related
library.add_relationship(9781984822185, 9780316517867)  # Mystery books related

# Search for related books starting from a specific book
print("\nSearching for books related to 'The Testaments' (ISBN: 9780345816023):")
library.search_related_books(9780345816023)

# Find and print all clusters of related books (connected components)
print("\nClusters of related books:")
clusters = library.find_related_clusters()
for idx, cluster in enumerate(clusters):
    print(f"Cluster {idx + 1}: {cluster}")

Book added: The Testaments by Margaret Atwood (Genre: Fiction)
Book added: The Nickel Boys by Colson Whitehead (Genre: Historical Fiction)
Book added: The Dutch House by Ann Patchett (Genre: Fiction)
Book added: Where the Crawdads Sing by Delia Owens (Genre: Mystery)
Book added: The Night Fire by Michael Connelly (Genre: Mystery)
Book added: Becoming by Michelle Obama (Genre: Biography)
Relationship established between ISBN 9780345816023 and ISBN 9780593139134
Relationship established between ISBN 9781984822185 and ISBN 9780316517867

Searching for books related to 'The Testaments' (ISBN: 9780345816023):
Visited book ISBN 9780345816023: The Testaments by Margaret Atwood (Genre: Fiction)
Visited book ISBN 9780593139134: The Dutch House by Ann Patchett (Genre: Fiction)

Clusters of related books:
Cluster 1: [The Testaments by Margaret Atwood (Genre: Fiction), The Dutch House by Ann Patchett (Genre: Fiction)]
Cluster 2: [The Nickel Boys by Colson Whitehead (Genre: Historical Fiction)]
Clu

1.Book Class:

    Represents a book in the library with attributes such as isbn, title, author, and genre.

    The __repr__ method formats the output when printing a book object.

2.LibraryGraph Class:

    graph: This is an adjacency list representing the relationships between books. Each book (node) is identified by its ISBN, and edges represent relationships with other books.

    add_book: Adds a book (node) to the graph. Each book is represented by its ISBN.

    add_relationship: Adds an edge (relationship) between two books based on ISBN.
    
    This relationship might represent books of the same genre, by the same author, etc.

    search_related_books: Uses DFS to explore and print all books related to a given book (identified by its ISBN).

    find_related_clusters: Finds all connected components (clusters) of related books. Each cluster represents a group of related books that are connected through one or more relationships.

    get_book_by_isbn: Helper method to retrieve a book object by its ISBN.


3.Global List books:

    This is a list of book objects to be added to the library. Each book has an ISBN, title, author, and genre.


4.DFS for Related Books:

    Starting from a given book, DFS explores all related books recursively, marking them as visited and printing their details.


5.Connected Components:

    Clusters of related books are found using DFS. Each cluster represents a group of books that are all related either directly or indirectly (through other books).


Explanation of Example Output:

    1. Adding Books: 
    All books are successfully added to the library graph.

    2. Adding Relationships: 

    Relationships are established between books of the same genre:

    
    "The Testaments" and "The Dutch House" (both Fiction).
    "Where the Crawdads Sing" and "The Night Fire" (both Mystery).

    3.	Search Related Books: Starting from "The Testaments", we find that "The Dutch House" is related to it (since they both belong to Fiction).

    4.Finding Clusters: We find 4 clusters (connected components) of books:

    o	Cluster 1: Fiction books.
    o	Cluster 2: Mystery books.
    o	Cluster 3: "The Nickel Boys" (Historical Fiction).
    o	Cluster 4: "Becoming" (Biography).
