In [6]:
import numpy as np
from numpy import array, matrix

List1 = [1, 2, 3, 4, 5]

print(List1)

List2 = [6, 7, 8, 9, 10]

print(List2)

print(List1 + List2)

array1 = array(List1)

print(array1) # [1 2 3 4 5]

array2 = array(List2)

print(array2) # [ 6  7  8  9 10]

array3 = array1 + array2

print(array3) # [ 7  9 11 13 15]

add = lambda var1, var2: var1 + var2

print(add(1, 2)) # 3

result = list(map(add, List1, List2))
print(result)

[1, 2, 3, 4, 5]
[6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1 2 3 4 5]
[ 6  7  8  9 10]
[ 7  9 11 13 15]
3
[7, 9, 11, 13, 15]


In [13]:
print(list(map(lambda var1, var2 : [var1**3, var2**3 ], List1, List2)))

books = [ 'python','jython','scala','dotnet','java']

print(list(map(lambda var1 : var1.upper(), books)))

[[1, 216], [8, 343], [27, 512], [64, 729], [125, 1000]]
['PYTHON', 'JYTHON', 'SCALA', 'DOTNET', 'JAVA']


In [20]:
def even_odd(var1):
                    ''' Even or Odd number'''
                    if var1 % 2 == 0:
                                        return True
                    else:
                                        return False

print(list(map(even_odd, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])))

print(list(filter(even_odd, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])))
print(list(filter(lambda var1 : var1 % 2 == 0, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])))

[False, True, False, True, False, True, False, True, False, True]
[2, 4, 6, 8, 10]
[2, 4, 6, 8, 10]


In [24]:
print(list(filter(lambda var1 : var1 % 3 == 0, [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])))

print(list(filter(lambda var: var % 2 !=0 and var % 3 != 0, range(1,25))))

[3, 6, 9]
[1, 5, 7, 11, 13, 17, 19, 23]


In [1]:
list3 = list(zip([1, 2, 3], [4, 5, 6]))
print(list3)

[(1, 4), (2, 5), (3, 6)]


In [44]:
Que = ['name','age','city','state','country']
Ans = ['Suresh', 25, 'Hyderabad', 'Telangana', 'India']

print(list(zip(Que, Ans)))

for q, a in zip(Que, Ans):
                    print('What is your {0}? It is {1}.'.format(q, a))



[('name', 'Suresh'), ('age', 25), ('city', 'Hyderabad'), ('state', 'Telangana'), ('country', 'India')]
What is your name? It is Suresh.
What is your age? It is 25.
What is your city? It is Hyderabad.
What is your state? It is Telangana.
What is your country? It is India.
{'name': 'Suresh', 'age': 25, 'city': 'Hyderabad', 'state': 'Telangana', 'country': 'India'}


In [48]:
QA = dict(zip(Que, Ans))
print(QA)

dict1 = { key.upper() : value for key, value in QA.items() if key != 'name' and key != 'age'}

print(dict1)

{'name': 'Suresh', 'age': 25, 'city': 'Hyderabad', 'state': 'Telangana', 'country': 'India'}
{'CITY': 'Hyderabad', 'STATE': 'Telangana', 'COUNTRY': 'India'}


In [15]:
Que = ['name','age','city','state','country']
Ans = ['Suresh', 25, 'Hyderabad', 'Telangana', 'India']
Ans1 = ['Surbhi', 26, 'Bangalore', 'Karanataka', 'India']

answers = list(zip(Ans, Ans1))

QA = dict(zip(Que, answers))

print(QA)

print(QA.items())

for q, a in QA.items():
                    print('What is your {0}? It is {1}.'.format(q, a))

{'name': ('Suresh', 'Surbhi'), 'age': (25, 26), 'city': ('Hyderabad', 'Bangalore'), 'state': ('Telangana', 'Karanataka'), 'country': ('India', 'India')}
dict_items([('name', ('Suresh', 'Surbhi')), ('age', (25, 26)), ('city', ('Hyderabad', 'Bangalore')), ('state', ('Telangana', 'Karanataka')), ('country', ('India', 'India'))])
What is your name? It is ('Suresh', 'Surbhi').
What is your age? It is (25, 26).
What is your city? It is ('Hyderabad', 'Bangalore').
What is your state? It is ('Telangana', 'Karanataka').
What is your country? It is ('India', 'India').


In [25]:
import pandas as pd

df = pd.DataFrame(QA)
print(df)
print(df['name'])
print(df['age'])
print(df.shape)
print(df[1:2])

df.describe()

     name  age       city       state country
0  Suresh   25  Hyderabad   Telangana   India
1  Surbhi   26  Bangalore  Karanataka   India
0    Suresh
1    Surbhi
Name: name, dtype: object
0    25
1    26
Name: age, dtype: int64
(2, 5)
     name  age       city       state country
1  Surbhi   26  Bangalore  Karanataka   India


age
count   2.000000
mean   25.500000
std     0.707107
min    25.000000
25%    25.250000
50%    25.500000
75%    25.750000
max    26.000000

In [27]:
data = '''Insertion Operation:
Time Complexity:
Best Case (O(1)): Inserting at the end of the array (no shifting required).
Worst Case (O(n)): Inserting at the beginning of the array (shifting all elements).
Average Case (O(n/2) ≈ O(n)): Inserting in the middle, which requires shifting half of the elements.
Space Complexity:
O(1): Only a constant amount of additional space is needed to store the new element temporarily.
Deletion Operation:
Time Complexity:
Best Case (O(1)): Deleting the last element (no shifting required).
Worst Case (O(n)): Deleting the first element (shifting all elements).
Average Case (O(n/2) ≈ O(n)): Deleting from the middle, which requires shifting half of the elements.
Space Complexity:
O(1): Only a constant amount of additional space is required to manage the deletion process.'''

# print(data)

split_data = data.split('\n')
print(split_data)

['Insertion Operation:', 'Time Complexity:', 'Best Case (O(1)): Inserting at the end of the array (no shifting required).', 'Worst Case (O(n)): Inserting at the beginning of the array (shifting all elements).', 'Average Case (O(n/2) ≈ O(n)): Inserting in the middle, which requires shifting half of the elements.', 'Space Complexity:', 'O(1): Only a constant amount of additional space is needed to store the new element temporarily.', 'Deletion Operation:', 'Time Complexity:', 'Best Case (O(1)): Deleting the last element (no shifting required).', 'Worst Case (O(n)): Deleting the first element (shifting all elements).', 'Average Case (O(n/2) ≈ O(n)): Deleting from the middle, which requires shifting half of the elements.', 'Space Complexity:', 'O(1): Only a constant amount of additional space is required to manage the deletion process.']


In [31]:
enumerate_data = list(enumerate(split_data, 1))
print(enumerate_data)

[(1, 'Insertion Operation:'), (2, 'Time Complexity:'), (3, 'Best Case (O(1)): Inserting at the end of the array (no shifting required).'), (4, 'Worst Case (O(n)): Inserting at the beginning of the array (shifting all elements).'), (5, 'Average Case (O(n/2) ≈ O(n)): Inserting in the middle, which requires shifting half of the elements.'), (6, 'Space Complexity:'), (7, 'O(1): Only a constant amount of additional space is needed to store the new element temporarily.'), (8, 'Deletion Operation:'), (9, 'Time Complexity:'), (10, 'Best Case (O(1)): Deleting the last element (no shifting required).'), (11, 'Worst Case (O(n)): Deleting the first element (shifting all elements).'), (12, 'Average Case (O(n/2) ≈ O(n)): Deleting from the middle, which requires shifting half of the elements.'), (13, 'Space Complexity:'), (14, 'O(1): Only a constant amount of additional space is required to manage the deletion process.')]


In [32]:
for line in enumerate(split_data, 1):
    print(line)

(1, 'Insertion Operation:')
(2, 'Time Complexity:')
(3, 'Best Case (O(1)): Inserting at the end of the array (no shifting required).')
(4, 'Worst Case (O(n)): Inserting at the beginning of the array (shifting all elements).')
(5, 'Average Case (O(n/2) ≈ O(n)): Inserting in the middle, which requires shifting half of the elements.')
(6, 'Space Complexity:')
(7, 'O(1): Only a constant amount of additional space is needed to store the new element temporarily.')
(8, 'Deletion Operation:')
(9, 'Time Complexity:')
(10, 'Best Case (O(1)): Deleting the last element (no shifting required).')
(11, 'Worst Case (O(n)): Deleting the first element (shifting all elements).')
(12, 'Average Case (O(n/2) ≈ O(n)): Deleting from the middle, which requires shifting half of the elements.')
(13, 'Space Complexity:')
(14, 'O(1): Only a constant amount of additional space is required to manage the deletion process.')


In [42]:
books = ['python','jython','scala','dotnet','java','python','java','jython']
print(books)
book1 = ['python1','jython1','scala','dotnet','java1','python','java','jython']
print(book1)

books_set = set(books)

print(books_set)

books_set1 = set(book1)

print('python' in books_set)

sorted_books = sorted(books_set)

print(sorted_books)

union_books = books_set.union(books_set1)

print(union_books)

intersection_books = books_set.intersection(books_set1)

print(intersection_books)

difference_books = books_set.difference(books_set1)

print(difference_books)



['python', 'jython', 'scala', 'dotnet', 'java', 'python', 'java', 'jython']
['python1', 'jython1', 'scala', 'dotnet', 'java1', 'python', 'java', 'jython']
{'dotnet', 'java', 'python', 'scala', 'jython'}
True
['dotnet', 'java', 'jython', 'python', 'scala']
{'dotnet', 'java', 'python', 'scala', 'jython', 'python1', 'jython1', 'java1'}
{'dotnet', 'java', 'python', 'scala', 'jython'}
set()


In [43]:
# bitwise operations on set
print(books_set | books_set1)
print(books_set & books_set1)
print(books_set - books_set1)
print(books_set ^ books_set1)

{'dotnet', 'java', 'python', 'scala', 'jython', 'python1', 'jython1', 'java1'}
{'dotnet', 'java', 'python', 'scala', 'jython'}
set()
{'python1', 'jython1', 'java1'}


add',
 'clear',
 'copy',
 'difference',
 'difference_update',
 'discard',
 'intersection',
 'intersection_update',
 'isdisjoint',
 'issubset',
 'issuperset',
 'pop',
 'remove',
 'symmetric_difference',
 'symmetric_difference_update',
 'union',
 'update'

In [53]:
print(list(reversed(books)))

print(list(reversed('SURENDRA')))

print(list(reversed(range(1, 10))))

tuple1 = (1, 2, 3, 4, 5)
print(tuple1)

print(tuple(reversed(tuple1)))

['jython', 'java', 'python', 'java', 'dotnet', 'scala', 'jython', 'python']
['A', 'R', 'D', 'N', 'E', 'R', 'U', 'S']
[9, 8, 7, 6, 5, 4, 3, 2, 1]
(1, 2, 3, 4, 5)
(5, 4, 3, 2, 1)
